USE [master]
GO
CREATE DATABASE [vexteams24] CONTAINMENT = NONE ON PRIMARY 
( NAME = N'vexteams24', FILENAME = N'd:\data\vexteams24.mdf' , SIZE = 128MB , MAXSIZE = UNLIMITED , FILEGROWTH = 64MB )
 LOG ON
( NAME = N'vexteams24_log', FILENAME = N'e:\log\vexteams24_log.ldf' , SIZE = 1GB , MAXSIZE = 1GB , FILEGROWTH = 0MB )
   COLLATE SQL_Latin1_General_CP1_CI_AS WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

ALTER DATABASE [vexteams24] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [vexteams24] SET ANSI_NULLS OFF
GO

ALTER DATABASE [vexteams24] SET ANSI_PADDING OFF
GO

ALTER DATABASE [vexteams24] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [vexteams24] SET ARITHABORT OFF
GO

ALTER DATABASE [vexteams24] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [vexteams24] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [vexteams24] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [vexteams24] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [vexteams24] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [vexteams24] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [vexteams24] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [vexteams24] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [vexteams24] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [vexteams24] SET DISABLE_BROKER
GO

ALTER DATABASE [vexteams24] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [vexteams24] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [vexteams24] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [vexteams24] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [vexteams24] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [vexteams24] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [vexteams24] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [vexteams24] SET RECOVERY FULL
GO

ALTER DATABASE [vexteams24] SET  MULTI_USER
GO

ALTER DATABASE [vexteams24] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [vexteams24] SET DB_CHAINING OFF
GO

ALTER DATABASE [vexteams24] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [vexteams24] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [vexteams24] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [vexteams24] SET ACCELERATED_DATABASE_RECOVERY = OFF
GO

ALTER DATABASE [vexteams24] SET QUERY_STORE = OFF
GO

ALTER DATABASE [vexteams24] SET READ_WRITE
GO
