sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i 04-fn_extract_team_no.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i 05-p_generate_unique_random_string.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_add_url.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_add_urlLog.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_add_user.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_add_user_session.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_add_url.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_authenticate_mobile_user.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_check_email_availability.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_check_shorturl_availability.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_create_mobile_session.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_create_password_reset_token.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_delete_url.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_delete_user_profile.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_get_redirectionTypes.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_get_roles.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_get_teams.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_get_url.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_get_url_log.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_get_url_logs.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_get_urls.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_get_user_by_email.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_terminate_mobile_session.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_update_refresh_token.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_update_user_profile.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_validate_device_certificate.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_validate_password_reset_token.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_validate_refresh_token.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_api_validate_session.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_authenticate_user.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_delete_cookie.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_delete_url.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_get_target_url.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_get_url_by_id.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_get_url_history.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_get_urls.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_get_user_password_hash.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_is_shortUrl_registered.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_list_api_dashboard.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_list_html_redirectionTypes.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_list_html_teams.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_list_urls.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_update_password.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i p_validate_and_extend_session.sql
sqlcmd -U vexteams24_dbo -P INSERT_STRONG_PASSWORD_HERE -d vexteams24 -S REPLACE_SQL_SERVER_HOST,1433 -i grant_permissions.sql
